In [48]:
from __future__ import print_function

In [49]:
#ensure that GPU driver and CUDA is enabled and accesible by PyTorch
import torch
torch.cuda.is_available()

print(torch.__version__)


1.1.0


In [51]:
def activation(x) :
    """
    x: torch.Tensor
    sigmoid function
    """
    return 1 / (1 + torch.exp(-x))

#Generate data, reproducibility
torch.manual_seed(7)
#Generate random features : 1 row, 5 columns
features = torch.randn((1, 5))
#Generate a single value for bias
bias = torch.randn ((1, 1)) 
#Generate true weights with the same shape than features, normal distribution
weights = torch.rand_like(features)

"""
There are 2 ways to get output in the neural network
- Sum of multiplication of tensor
- Multiplication of matrices
"""

#Slow way: Sum and multiplication of single value
output = activation(torch.sum(features * weights))
print("first way ",output)
#Multiplication of matrices, fast way
#it can use : reshape, resize_ or view
output2 = activation(torch.mm(features, weights.view(5,1)))
print("second way ",output2)

first way  tensor(0.7956)
second way  tensor([[0.7956]])


In [74]:
"""
NOTE IN-PLACE Operations : _ form
change the value of the tensor without making a copy
"""
x = torch.rand(1)
y = torch.rand(1)
x = x + y
print(x)

x.add_(y)
print(x)

tensor([0.4132])
tensor([1.1704])
tensor([1.9276])
