In [2]:
from __future__ import print_function

In [3]:
#ensure that GPU driver and CUDA is enabled and accesible by PyTorch
import torch
torch.cuda.is_available()

print(torch.__version__)


1.1.0


In [4]:
def activation(x) :
    """
    x: torch.Tensor
    sigmoid function
    """
    return 1 / (1 + torch.exp(-x))

#Generate data, reproducibility
torch.manual_seed(7)
#Generate random features : 1 row, 5 columns
features = torch.randn((1, 5))
#Generate a single value for bias
bias = torch.randn ((1, 1)) 
#Generate true weights with the same shape than features, normal distribution
weights = torch.rand_like(features)

"""
There are 2 ways to get output in the neural network
- Sum of multiplication of tensor
- Multiplication of matrices
"""

#Slow way: Sum and multiplication of single value
output = activation(torch.sum(features * weights))
print("first way ",output)
#Multiplication of matrices, fast way
#it can use : reshape, resize_ or view
output2 = activation(torch.mm(features, weights.view(5,1)))
print("second way ",output2)

first way  tensor(0.7956)
second way  tensor([[0.7956]])


In [5]:
"""
NOTE IN-PLACE Operations : _ form
change the value of the tensor without making a copy
"""
x = torch.rand(1)
y = torch.rand(1)
x = x + y
print(x)

x.add_(y)
print(x)

tensor([1.0430])
tensor([2.0129])


In [6]:
"""
Stack tensors
"""
torch.manual_seed(7)
features = torch.randn((1, 3))
features.type()
n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn((n_input, n_hidden))
W2 = torch.randn((n_hidden, n_output))

b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

#get output
o_hidden = activation(torch.mm(features, W1) + b1)
o_output = activation(torch.mm(o_hidden, W2) + b2)

print(o_output)

tensor([[0.3171]])


In [10]:
"""
NOTE Numpy to Torch and back
"""
import numpy as np

a = np.random.rand(4,3)
a

array([[0.49950258, 0.76548645, 0.44373702],
       [0.34757295, 0.3879043 , 0.99594931],
       [0.85260572, 0.4273266 , 0.33124107],
       [0.88712654, 0.6028963 , 0.06362281]])

In [11]:
b = torch.from_numpy(a)
b

tensor([[0.4995, 0.7655, 0.4437],
        [0.3476, 0.3879, 0.9959],
        [0.8526, 0.4273, 0.3312],
        [0.8871, 0.6029, 0.0636]], dtype=torch.float64)

In [12]:
b.numpy()

array([[0.49950258, 0.76548645, 0.44373702],
       [0.34757295, 0.3879043 , 0.99594931],
       [0.85260572, 0.4273266 , 0.33124107],
       [0.88712654, 0.6028963 , 0.06362281]])

In [15]:
#The memory is share between torch and numpy
b.mul_(2)

tensor([[1.9980, 3.0619, 1.7749],
        [1.3903, 1.5516, 3.9838],
        [3.4104, 1.7093, 1.3250],
        [3.5485, 2.4116, 0.2545]], dtype=torch.float64)

In [14]:
a

array([[0.99900516, 1.53097289, 0.88747403],
       [0.69514589, 0.77580861, 1.99189861],
       [1.70521143, 0.8546532 , 0.66248214],
       [1.77425307, 1.20579261, 0.12724561]])